{
 "title": "Mi App - Metricas HTTP y Recursos",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Peticiones por segundo (por ruta)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(demo_app_http_requests_total[1m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Latencia p95 (segundos)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(demo_app_http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Errores 5xx por segundo",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(demo_app_http_requests_total{status_code=~\"5..\"}[1m]))",
     "legendFormat": "errores"
    }
   ]
  },
  {
   "title": "Memoria usada por el Pod",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"demo-app.*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}